#!/bin/bash
cd "${0%/*}"/..
touch .env
mkdir logs
mkdir logs/nginx

cp src/config.php.copy src/config.php

printf "PG_DB_NAME=main
PG_DB_USER=myuser
PG_DB_PASSWORD=mypassword"> .env
#yum install php-pgsql php-pdo_pgsql
#Install this if Phinx is broken on Fedora/Centos

echo Start the docker container then run ./local/mig